name: Tests

on: ['push', 'pull_request']

permissions: read-all

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3, 8.4, 8.5]
        symfony: [false]
        dependency: [stable]
        include:
          - { php: 8.2, symfony: ^6.4 , dependency: stable }
          - { php: 8.4, symfony: ^7.4, dependency: highest }
          - { php: 8.4, symfony: false, dependency: highest }

    env:
      SYMFONY_REQUIRE: ${{ matrix.symfony }}

    name: Tests P${{ matrix.php }} - SF${{ matrix.symfony }} - ubuntu-latest - ${{ matrix.dependency }}
    steps:

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, mbstring, zip
          coverage: none
          tools: flex

      - name: Install Composer dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # v4
        with:
          dependency-versions: ${{ matrix.dependency }}

      - name: Integration Tests
        run: php ./vendor/bin/phpunit
